# Generated by Django 4.2.3 on 2023-07-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HVAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvacName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HVAC_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton_in_hvac_type', models.CharField(choices=[('3/4', '3/4 Ton'), ('1', '1 Ton')], default='3/4', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(help_text="Enter the Site's building type followed by its number. (e.g. B1, S12, W6, X01)", max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModelName',
        ),
        migrations.AddField(
            model_name='hvac',
            name='hvacType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.hvac_type'),
        ),
        migrations.AddField(
            model_name='hvac',
            name='site2hvac',
            field=models.ManyToManyField(help_text='Select a Site for thiS HVAC unit.', to='catalog.site'),
        ),
    ]
