# Generated by Django 4.2.3 on 2023-07-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_hvac_hvac_type_site_delete_mymodelname_hvac_hvactype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HVAC_Type',
            new_name='HVACType',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='siteName',
            new_name='site_Name',
        ),
        migrations.AddField(
            model_name='site',
            name='hvac_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='hvac_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.hvactype'),
        ),
        migrations.DeleteModel(
            name='HVAC',
        ),
    ]
