# Generated by Django 4.2.3 on 2023-07-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_hvac_type_hvactype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='hvac_Name',
        ),
        migrations.AddField(
            model_name='hvactype',
            name='hvac_Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
