# Generated by Django 4.2.3 on 2023-07-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_hvactype_hvac_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HVAC_Type',
            new_name='HVACType',
        ),
    ]
