# Generated by Django 4.2.3 on 2023-07-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_hvac_type_hvactype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='hvac_Type',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_Name',
        ),
        migrations.AddField(
            model_name='site',
            name='site_access_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='site',
            name='site_agent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='site_emergency_power',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_generator',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_id',
            field=models.IntegerField(auto_created=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_lat',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=7),
        ),
        migrations.AddField(
            model_name='site',
            name='site_long',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=7),
        ),
        migrations.AddField(
            model_name='site',
            name='site_notes',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='site',
            name='site_power',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_power_account',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_short_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_zip',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='site',
            name='site_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
