# Generated by Django 4.2.3 on 2023-07-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_choice_alter_site_site_emergency_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_emergency_power',
            field=models.CharField(help_text='Yes, no, or uknown', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='choice',
        ),
    ]
