# Generated by Django 4.2.3 on 2023-07-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_site_site_generator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_generator',
            field=models.CharField(help_text='Cummins, Generac, None, or Unknown', max_length=10, null=True),
        ),
    ]
