# Generated by Django 4.2.3 on 2023-08-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_site_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='site',
        ),
    ]
