# Generated by Django 4.2.3 on 2023-08-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_site_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_lat',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_long',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
