# Generated by Django 4.2.3 on 2023-08-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_site_site_lat_alter_site_site_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_lat',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=25),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_long',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=25),
        ),
    ]
