# Generated by Django 4.2.3 on 2023-08-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_site_site_lat_alter_site_site_long'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HVACType',
        ),
    ]
