# Generated by Django 4.2.3 on 2023-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_delete_hvactype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.IntegerField(auto_created=True, default=None, primary_key=True, serialize=False),
        ),
    ]
