# Generated by Django 4.2.3 on 2023-08-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_site_id_alter_site_site_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='site2',
        ),
    ]
